import React from "react";
import { Metadata } from "next";
import "@/app/globals.css";
import ThemeProviderWrapper from "@/app/ThemeProviderWrapper";

export const metadata: Metadata = {
  title: {
    template: '%s | Jiro Housing',
    default: 'Jiro Housing',
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body>
        <ThemeProviderWrapper>
          {children}
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}

